export const mocks = [
    {
      name: "Apple AirPods Pro",
      id: "MLXJ2LL/A",
      type: "in-ear",
      max_volume: "80 dB",
      brand: "Apple",
      reviews: [
        "Потрясающий дизайн и комфорт.",
        "Отличное качество звука.",
        "Хорошо работают с iPhone.",
      ],
      codecs: ["SBC", "AAC"],
      price: 10,
    },
    {
      name: "Sony WF-1000XM3",
      id: "WF1000XM3V",
      type: "true wireless",
      max_volume: "100 dB",
      brand: "Sony",
      reviews: ["Отличный звук.", "Удобное управление.", "Хорошая автономность."],
      codecs: ["LDAC", "AAC", "SBC"],
      price: 10,
    },
    {
      name: "Sennheiser Momentum 3",
      id: "M3IEG",
      type: "on-ear",
      max_volume: "120 dB",
      brand: "Sennheiser",
      reviews: [
        "Высокое качество звука.",
        "Комфортные в ношении.",
        "Стильный дизайн.",
      ],
      codecs: ["aptX", "AAC", "SBC"],
      price: 10,
    },
    {
      name: "Bose QuietComfort 35 II",
      id: "794418",
      type: "over-ear",
      max_volume: "115 dB",
      brand: "Bose",
      reviews: [
        "Отличная шумоизоляция.",
        "Качественный звук.",
        "Удобные амбушюры.",
      ],
      codecs: ["AAC", "SBC"],
      price: 10,
    },
    {
      name: "Marshall Major IV",
      id: "MARSHALLMAJORIVBLK",
      type: "on-ear",
      max_volume: "99 dB",
      brand: "Marshall",
      reviews: ["Хорошее звучание.", "Долго держат заряд.", "Легкие и удобные."],
      codecs: ["aptX", "aptX HD", "AAC", "SBC"],
      price: 10,
    },
    {
      name: "Beats Studio 3",
      id: "HTCIA62",
      type: "on-ear",
      max_volume: "98 dB",
      brand: "Beats",
      reviews: ["Отличные басы.", "Хороший звук в целом.", "Стильные и удобные."],
      codecs: ["AAC", "SBC"],
      price: 10,
    },
    {
      name: "Anker Soundcore Life Q30",
      id: "A3153301",
      type: "on-ear",
      max_volume: "96 dB",
      brand: "Anker",
      reviews: [
        "Глубокие басы.",
        "Качественная сборка.",
        "Достойный звук за свою цену.",
      ],
      codecs: ["aptX", "AAC", "SBC"],
      price: 10,
    },
    {
      name: "Panasonic RZ-S300WGE",
      id: "RZ-S300WGE-K",
      type: "true wireless",
      max_volume: "90 dB",
      brand: "Panasonic",
      reviews: [
        "Хороший звук и шумодав.",
        "Комфортно сидят в ушах.",
        "Долго держат заряд.",
      ],
      codecs: ["AAC", "SBC"],
      price: 10,
    },
    {
      name: "Shure AONIC 5",
      id: "SH-AONIC5",
      type: "closed-back",
      max_volume: "97 dB",
      brand: "Shure",
      reviews: [
        "Превосходное качество звука.",
        "Стильный и современный дизайн.",
        "Комфортные и легкие.",
      ],
      codecs: ["aptX LL", "LDAC", "AAC", "SBC"],
      price: 10,
    },
  ];